'Solution'
mate-academy/py-delivery-drone pull request #1133
Opened 2024-07-25 19:41 UTC by RToister

2024-07-25 19:47 UTC, vasylhnatiuk requested changes

2024-07-25 19:47 UTC, vasylhnatiuk commented on app/main.py
> +                 coords: list | None = None
```suggestion
                 coords: list[int] | None = None
```

2024-07-25 19:47 UTC, vasylhnatiuk commented on app/main.py
> +            weight: int, coords: list | None = None,
same here

2024-07-25 19:47 UTC, vasylhnatiuk commented on app/main.py
> +        if coords is None:
use or here as well

2024-07-25 20:11 UTC, RToister commented on app/main.py
> +            weight: int, coords: list | None = None,
Thanks, will fixed

2024-07-26 05:39 UTC, RToister commented
Hello. I try to understand why I can't make one more pull request after first (  
for Solution3

2024-07-28 19:20 UTC, closed without merging