'Solution'
mate-academy/py-delivery-drone pull request #137
Opened 2022-09-19 12:33 UTC by AVyha

2022-09-20 16:04 UTC, wQuelS requested changes

2022-09-20 16:04 UTC, wQuelS commented on app/main.py
> +class BaseRobot(Cargo):
Does BaseRobot class really need to inherite from Cargo?

2022-09-20 16:21 UTC, AVyha commented on app/main.py
> +class BaseRobot(Cargo):
i think really need because in readme write something like this
![image](https://user-images.githubusercontent.com/80789163/191311980-5b937ee5-849f-44d6-b72b-3cd3b83e5d3e.png)

2022-09-20 16:27 UTC, wQuelS commented on app/main.py
> +class BaseRobot(Cargo):
Ok, i guess task is not that clear. Mentor will answer that question anyway:)

2022-09-20 16:27 UTC, wQuelS approved these changes

2022-09-20 16:28 UTC, AVyha commented on app/main.py
> +class BaseRobot(Cargo):
Thanks for the review

2022-09-26 18:16 UTC, Nattalli requested changes

2022-09-26 18:16 UTC, Nattalli commented on app/main.py
> +class BaseRobot(Cargo):
@wQuelS is right. That class should not be a child of `Cargo`. The task is to create 3 classes (it is their general count) and use the inheritance (but it doesn't mean that every class should use the inheritance)

2022-09-26 18:16 UTC, Nattalli commented on app/main.py
> +    def __init__(self, name: str, weight: int, coords: list = None) -> None:
it's better to use `list[int]` here

2022-09-26 18:16 UTC, Nattalli commented on app/main.py
> +                 coords: list = None) -> None:
it's better to use `list[int]` here

2022-09-26 18:16 UTC, Nattalli commented on app/main.py
> +                 coords: list = None) -> None:
it's better to use `list[int]` here

2022-09-27 11:49 UTC, Nattalli approved these changes
Well done! 👍🏻

2024-12-01 14:38 UTC, closed without merging