Solution
mate-academy/py-delivery-drone pull request #139
Opened 2022-09-20 14:45 UTC by StasOkhrym

2022-09-20 22:26 UTC, IvanStored requested changes

2022-09-20 22:26 UTC, IvanStored commented on app/main.py
> +                 current_load: int
why DeliveryDrone doesn't accept `coords` argument?

2022-09-21 09:31 UTC, IvanStored approved these changes

2022-09-26 17:57 UTC, Nattalli requested changes

2022-09-26 17:57 UTC, Nattalli commented on app/main.py
>      def __init__(self, weight):
add type anotation

2022-09-26 17:57 UTC, Nattalli commented on app/main.py
> +                 coords: list = None):
it's better to use `list[int]` here

2022-09-26 17:57 UTC, Nattalli commented on app/main.py
> +                 coords: list = None):
it's better to use `list[int]` here

2022-09-26 17:57 UTC, Nattalli commented on app/main.py
> +                 coords: list = None):
it's better to use `list[int]` here

2022-09-26 18:37 UTC, Nattalli approved these changes
Good job!

2024-06-03 11:00 UTC, closed without merging