solve the task
mate-academy/py-delivery-drone pull request #178
Opened 2022-09-26 13:56 UTC by Cerne13

2022-09-26 14:24 UTC, Vasyl-Poremchuk approved these changes
GJ!

2022-09-26 17:39 UTC, Nattalli requested changes

2022-09-26 17:39 UTC, Nattalli commented on app/main.py
> +    def __init__(self, weight: int):
add type annotation for function. if it returns nothing then use `-> None`

2022-09-26 17:39 UTC, Nattalli commented on app/main.py
> +            list[int] = None
can it be in one line?

2022-09-26 17:39 UTC, Nattalli commented on app/main.py
> +            list[int] = None
and here

2022-09-26 20:43 UTC, Cerne13 commented on app/main.py
> +    def __init__(self, weight: int):
Thank you!

2022-09-27 06:46 UTC, Nattalli approved these changes
Good job! 😸

2022-12-09 09:05 UTC, closed without merging