Develop
mate-academy/py-delivery-drone pull request #188
Opened 2022-09-26 18:05 UTC by pazyn404

I modify tests cause original doesn't even run. I just delete block for another version, so it's not cheating)

2022-09-26 18:59 UTC, StasOkhrym approved these changes

2022-09-26 18:59 UTC, StasOkhrym commented on app/main.py
> +
Here as well
but it's up to you

2022-09-26 18:59 UTC, StasOkhrym commented on app/main.py
> +            self.coords = [0, 0]
You could implement coord initialization it a bit easier

2022-09-26 18:59 UTC, StasOkhrym commented on app/main.py
> +
no need to use deepcopy, imho.

2022-09-26 19:04 UTC, Nattalli requested changes

2022-09-27 09:29 UTC, Nattalli approved these changes
Awesome! 😎

2025-08-20 09:53 UTC, closed without merging