Solution
mate-academy/py-delivery-drone pull request #218
Opened 2022-10-27 15:07 UTC by ArtMot99

2022-10-27 17:12 UTC, Abnormaltype requested changes

2022-10-27 17:12 UTC, Abnormaltype commented on app/main.py
> +
you can write this in one line

2022-10-31 15:25 UTC, IvanRamyk requested changes

2022-11-01 09:20 UTC, ArtMot99 commented on app/main.py
> +        super().__init__(name, weight, [0, 0, 0]) if coords is None else \
How?

2022-11-04 11:07 UTC, IvanRamyk approved these changes
Well done!

2024-03-12 16:56 UTC, closed without merging