Solution
mate-academy/py-delivery-drone pull request #238
Opened 2022-11-22 14:16 UTC by T-Vlad-96

2022-11-23 09:44 UTC, Abnormaltype requested changes

2022-11-23 09:44 UTC, Abnormaltype commented on app/main.py
> +            coords = [0, 0]
you can write this in one line

2022-11-23 09:44 UTC, Abnormaltype commented on app/main.py
> +            coords = [0, 0, 0]
the same

2022-11-23 09:44 UTC, Abnormaltype commented on app/main.py
> +            coords = [0, 0, 0]
the same

2022-12-01 12:34 UTC, IvanRamyk requested changes

2022-12-01 12:34 UTC, IvanRamyk commented on app/main.py
> +        coords = [0, 0, 0] if coords is None else coords
extra variable

2022-12-09 08:39 UTC, Abnormaltype approved these changes

2025-11-02 11:34 UTC, closed without merging