solution
mate-academy/py-delivery-drone pull request #249
Opened 2022-12-02 21:52 UTC by AlexanderTsvirko

2022-12-03 13:14 UTC, OleksandrPozden requested changes

2022-12-03 13:14 UTC, OleksandrPozden commented on app/main.py
> +            self.coords = coords
write it in one line

2022-12-03 13:14 UTC, OleksandrPozden commented on app/main.py
> +            self.coords = coords
in one line

2022-12-03 13:21 UTC, AlexanderTsvirko commented on app/main.py
> +            self.coords = coords
Done

2022-12-03 13:39 UTC, OleksandrPozden requested changes

2022-12-03 13:39 UTC, OleksandrPozden commented on app/main.py
> +        self.coords = [0, 0] if coords is None else coords
Good, but you do it even more simple

2022-12-04 10:00 UTC, Serhii-Leonenko requested changes

2022-12-04 10:00 UTC, Serhii-Leonenko commented on app/main.py
> +        super().__init__(name, weight, coords)
```suggestion
        super().__init__(name, weight)
```

2022-12-04 15:46 UTC, OleksandrPozden requested changes

2022-12-04 15:46 UTC, OleksandrPozden commented on app/main.py
> +        self.coords = coords if coords else [0, 0]
yes, you have done a great job. but look at this simple solution
```suggestion
        self.coords = coords or [0, 0]
```

2022-12-04 15:46 UTC, OleksandrPozden commented on app/main.py
> +        self.coords = coords if coords else [0, 0, 0]
change it here, as well

2022-12-05 16:33 UTC, YuriiKindrat approved these changes

2024-03-12 17:13 UTC, closed without merging