Solution
mate-academy/py-delivery-drone pull request #368
Opened 2023-02-13 14:43 UTC by ProdyRodion

2023-02-14 11:20 UTC, oksanaaam approved these changes

2023-02-14 12:45 UTC, YuriiKindrat requested changes

2023-02-14 12:45 UTC, YuriiKindrat commented on app/main.py
> +        return self.coords
no need to return coords here

2023-02-14 12:45 UTC, YuriiKindrat commented on app/main.py
> +        self.coords = [0, 0, 0] if coords is None else coords
u can make this check inside super func, no need to rewrite attribute

2023-02-14 12:45 UTC, YuriiKindrat commented on app/main.py
> +        return self.coords
the same is for this returns

2023-02-14 12:45 UTC, YuriiKindrat commented on app/main.py
> +        current_load: int | None,
are u sure that current_load is int ?

2023-02-14 15:54 UTC, Serhii-Leonenko requested changes

2023-02-14 15:54 UTC, Serhii-Leonenko commented on app/main.py
> +            coords=[0, 0, 0] if coords is None else coords)
fix indentation here

2023-02-14 15:54 UTC, Serhii-Leonenko commented on app/main.py
> +        current_load: None,
I don't agree with the annotation for current_load, also use the default value for it

2023-02-15 14:02 UTC, Serhii-Leonenko requested changes

2023-02-15 14:02 UTC, Serhii-Leonenko commented on app/main.py
> +            coords: list = None
Sorry, I didn't say you before. But coords could be both types, for that purpose use annotation like this. The same in other similar cases

```suggestion
            coords: list | None = None
```

2023-02-15 15:52 UTC, wQuelS approved these changes
Nice

2026-03-11 21:00 UTC, closed without merging