Drones... Passes those tests at least
mate-academy/py-delivery-drone pull request #469
Opened 2023-05-24 16:08 UTC by thorium-zero

2023-05-26 13:06 UTC, YuriiKindrat requested changes

2023-05-26 13:06 UTC, YuriiKindrat commented on app/main.py
> +            return
no need to use if twice here, u can multiply them by "and", also no need to use blank returns here, u can use backward condition here

2023-05-26 13:06 UTC, YuriiKindrat commented on app/main.py
> +            return
same here

2023-05-31 12:06 UTC, thorium-zero commented on app/main.py
> +            return
yes, I could, but those are guard clauses, they're suppose to throw exceptions or... simply return... Also, it is actually better to split those "if" statements since I check for pretty different types of issues.

2023-06-05 13:05 UTC, YuriiKindrat requested changes

2023-06-05 13:05 UTC, YuriiKindrat commented on app/main.py
> +        current_load: int,
it seems to me, that current loas is not int )

2023-06-05 13:05 UTC, YuriiKindrat commented on app/main.py
> +        self._coords: list[int] = coords if coords is not None else [0, 0]
also u can simplify this like this `coords or [0,0]` this will also check for blank list

2023-06-05 14:21 UTC, thorium-zero commented on app/main.py
> +        current_load: int,
damn right it isn't :D

2023-07-27 10:45 UTC, closed without merging