resloved
mate-academy/py-delivery-drone pull request #535
Opened 2023-07-02 16:15 UTC by VladyslavShepilov

2023-07-02 16:47 UTC, vsmutok requested changes

2023-07-02 16:47 UTC, vsmutok commented on app/main.py
> +            coords = [0, 0, 0]
use `or`

2023-07-02 16:47 UTC, vsmutok commented on app/main.py
> +            self.coords = coords
use `or`

2023-07-03 08:45 UTC, ArsenPidhoretskyi approved these changes
Well done!

2025-10-24 20:38 UTC, closed without merging