'Solution'
mate-academy/py-delivery-drone pull request #641
Opened 2023-09-17 15:43 UTC by nsdNite

2023-09-17 19:45 UTC, Bohdan-Salamakha requested changes

2023-09-17 19:45 UTC, Bohdan-Salamakha commented on app/main.py
> +            coords: list = None
use typehint like: Optional[YOUR_VALUE_TYPE] = None
for example: list that contains string elements and can be None has typehint Optional[list[str]]
+
add additional typehint for list inner objects like list[YOUR_VALUE_TYPE]
for example: list that contains string elements has typehint list[str]

2023-09-17 19:45 UTC, Bohdan-Salamakha commented on app/main.py
> +            coords: list = None
use typehint like: Optional[YOUR_VALUE_TYPE] = None
for example: list that contains string elements and can be None has typehint Optional[list[str]]
+
add additional typehint for list inner objects like list[YOUR_VALUE_TYPE]
for example: list that contains string elements has typehint list[str]

2023-09-17 19:45 UTC, Bohdan-Salamakha commented on app/main.py
> +            coords: list = None
use typehint like: Optional[YOUR_VALUE_TYPE] = None
for example: list that contains string elements and can be None has typehint Optional[list[str]]
+
add additional typehint for list inner objects like list[YOUR_VALUE_TYPE]
for example: list that contains string elements has typehint list[str]

2023-09-18 05:15 UTC, nsdNite commented on app/main.py
> +            coords: list = None
done, thanks for comments
used Optional[List[int]] = None for coords list where it is used, no other lists in code.

2023-09-18 09:51 UTC, Dimosphen1 requested changes
Several changes were requested.

2023-09-18 09:51 UTC, Dimosphen1 commented on app/main.py
> +            self.coords = [0, 0]
You should prefer one style of the variable assignment in code, prefer picking up `or` as it is done on lines 65 and 46. Remove this `if ... else` condition and assign `self.coords` directly.

2023-09-18 09:51 UTC, Dimosphen1 commented on app/main.py
> +        coords = coords or [0, 0, 0]
You do not need to allocate `coords` variable here, pass this expression directly to the `super().__init__`

2023-09-18 09:51 UTC, Dimosphen1 commented on app/main.py
> +        coords = coords or [0, 0, 0]
You do not need to allocate `coords` variable here, pass this expression directly to the `super().__init__`

2023-09-18 15:21 UTC, nsdNite commented on app/main.py
> +            self.coords = [0, 0]
updated
thanks for comment

2023-09-18 15:21 UTC, nsdNite commented on app/main.py
> +        coords = coords or [0, 0, 0]
updated
thanks for comment

2023-09-18 15:21 UTC, nsdNite commented on app/main.py
> +        coords = coords or [0, 0, 0]
updated
thanks for comment

2023-09-18 16:38 UTC, Dimosphen1 approved these changes
LGTM, well done! One comment is left for consideration.

2023-09-18 16:38 UTC, Dimosphen1 commented on app/main.py
> +        super().__init__(name, weight, coords=coords or [0, 0, 0])
In case you pass the keyword arguments in the `__init__`, it would be better to pass other arguments with keys as well to be consistent and make sure that you do not produce ordering errors.

2023-09-18 17:35 UTC, nsdNite commented on app/main.py
> +        super().__init__(name, weight, coords=coords or [0, 0, 0])
Noted, thanks!

2025-04-08 11:45 UTC, closed without merging