Develop
mate-academy/py-delivery-drone pull request #661
Opened 2023-10-06 10:34 UTC by Daniil-Pankieiev

2023-10-07 08:53 UTC, prochigor approved these changes
I approve but look at the comment.

2023-10-07 08:53 UTC, prochigor commented on app/main.py
> +        self.coords = [0, 0] if coords is None else coords
Do you need else here?

2023-10-07 09:35 UTC, Daniil-Pankieiev commented on app/main.py
> +        self.coords = [0, 0] if coords is None else coords
Yes, it wont work without else

2023-10-10 19:53 UTC, fsocie7y requested changes

2023-10-10 19:53 UTC, fsocie7y commented on app/main.py
> +        if coords is None:
do this action as above) in one line
and u can move it in super.__init__()

2023-10-10 20:42 UTC, fsocie7y approved these changes
well done ^_^

2024-09-20 12:37 UTC, closed without merging