Solution
mate-academy/py-delivery-drone pull request #689
Opened 2023-10-10 14:17 UTC by SevKrok

2023-10-10 16:03 UTC, Oxbay approved these changes
Great work)

2023-10-10 18:04 UTC, fsocie7y requested changes

2023-10-10 18:04 UTC, fsocie7y commented on app/main.py
> +            coords = [0] * 2
you can write this in one line.  Use a single composite `if` statement

2023-10-10 18:04 UTC, fsocie7y commented on app/main.py
> +        if coords is None:
the same here, and also u can move it into super().__init__()

2023-10-11 09:31 UTC, fsocie7y approved these changes
well done ^_^

2023-10-11 09:48 UTC, closed without merging