'Solution'
mate-academy/py-delivery-drone pull request #70
Opened 2022-06-02 14:17 UTC by LaskoA

I hope this one will be better :)

2022-06-02 14:27 UTC, Abnormaltype requested changes

2022-06-02 14:27 UTC, Abnormaltype commented on app/main.py
> +            self.coords = [0, 0, 0]
that's not necessary

2022-06-02 14:27 UTC, Abnormaltype commented on app/main.py
> +            self.coords = [0, 0, 0]
You can write this in one line)

2022-06-02 14:27 UTC, Abnormaltype commented on app/main.py
> +            coords = [0, 0]
same here

2022-06-02 14:48 UTC, Abnormaltype requested changes

2022-06-03 07:17 UTC, LaskoA commented
Good morning :)

2022-06-03 07:27 UTC, Abnormaltype approved these changes
Good job!

2022-06-03 07:31 UTC, closed without merging