Solution
mate-academy/py-delivery-drone pull request #722
Opened 2023-10-28 17:56 UTC by AnyoneClown

2023-10-28 18:00 UTC, vsmutok requested changes

2023-10-28 18:00 UTC, vsmutok commented on app/main.py
> +            self.coords = coords
use `or` here

2023-10-29 09:28 UTC, viktoria-rybenchuk requested changes

2023-10-29 09:28 UTC, viktoria-rybenchuk commented on app/main.py
> +    def hook_load(self, other: Cargo) -> None:
use descriptive parameter name instead of `other`

2023-10-29 09:28 UTC, viktoria-rybenchuk commented on app/main.py
> +    def __init__(self, name: str, weight: int, coords: list = None) -> None:
specify type annotations for `coords`

2023-10-29 13:00 UTC, Polyakiv-Andrey approved these changes
Good job!

2024-05-23 19:20 UTC, closed without merging